### ISSUE TITLE
Empty Box

### ISSUE THREAD

**Issue by YaroKasear** [Damenly/homebrew-virt-manager#1]
I am trying to get virt-manager to work on my M1 Macbook Air and so far have had no luck with any repository I've tried. This one is the first one to at least not segfault or flat-out refuse to install.

Unfortunately when I launch it I simply get an empty box, no content or listings or controls of any kind. The --debug doesn't show anything going wrong. Is there a way to fix this problem?

**Comment by rafaelreis-r** [comment]
@Damenly your branch looks good as far as the segmentation faults go. I was able to install and run virt-manager on a M1 Air without the segfaults. Thanks. 

However I'm experiencing the empty box mentioned by the user above. 

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/57492577/139955567-c251e086-9cc7-428d-8f09-292bf3ec225a.png">

`CoreSVG has logged an error. Set environment variabe "CORESVG_VERBOSE" to learn more.`

I'm on MacOS 12 (Monterey), and I saw you fixed it for MacOS 11, so there could  be something associated to OS version. 

I'm avaliable to debug / test stuff for your branch on 12 if you'd guide me through it.

**Comment by Damenly** [comment]
@YaroKasear @rafaelreis-r Thanks for report! It's a known issue of gtk. Gtk repo already has fixes for it but not released. Here’s my temporary fix:

https://github.com/jeffreywildman/homebrew-virt-manager/issues/184#issuecomment-954768899

And no need to close the issue if it works. I will do it once new version of gtk is released to track the bug.

**Comment by Damenly** [comment]
The issue has been fixed by homebrew. Close it.
