### ISSUE TITLE
`glib-utils` replaced by `glib`

### ISSUE THREAD

**Issue by renzoe** [Damenly/homebrew-virt-manager#13]
https://github.com/Damenly/homebrew-virt-manager/blob/c6630948049bff564e0b68977d59a7afcdcff120/virt-viewer.rb#L16

This line is deprecated (`glib` aparently replaced `glib-utils` https://formulae.brew.sh/formula/glib).
My homebrew does not have a formulae to compile `glib-utils`;
Solution: I simply removed this dependency (`brew edit virt-viewer` then after edit `virt reinstall virt-viewer` ) and it worked.

**Comment by Damenly** [comment]
Fixed. Many thanks. brew upgrade is a pain for me so this repo is often outdated : (.
