### ISSUE TITLE
After last formula changes virt-viewer lost spice protocol support

### ISSUE THREAD

**Issue by k0ste** [Damenly/homebrew-virt-manager#6]
![Screen Shot 2022-08-10 at 15 46 24](https://user-images.githubusercontent.com/7759548/183904916-82cc69b6-3932-4487-ab06-6788aeb40926.png)
How-to add flag for meson we can see here, in Archlinux [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/virt-viewer/trunk/PKGBUILD#L25) 

Thanks

**Comment by Damenly** [comment]
Thanks. Added the arg to meson.

**Comment by k0ste** [comment]
Thanks, now spice works!
